--DDL DE PROYECTO--

SELECT * FROM USER_TABLES;

--DDL DE PROYECTO--

CREATE TABLE USUARIO (
nickName VARCHAR (30) NOT NULL,
direcciones VARCHAR(60) NOT NULL,
nroCasa CHARACTER (6) NOT NULL,
CONSTRAINT PK_USUARIO_nickName PRIMARY KEY (nickName) 
);

CREATE TABLE LOCALES(
idLocales INT NOT NULL, 
localNombre VARCHAR(30),
RUC VARCHAR(14),
horarioAtencion VARCHAR(100),
tarifaEnvio NUMBER,
CONSTRAINT PK_LOCALES_idLocales PRIMARY KEY (idLocales)
);

CREATE TABLE REPARTIDOR (
idRepar INT NOT NULL ,
nombreRapartidor VARCHAR (20) NOT NULL,
estado VARCHAR(10) NOT NULL,
CONSTRAINT PK_REPARTIDOR_idRepar PRIMARY KEY (idRepar)
);

CREATE TABLE PROMOCION (
idPromocion INT NOT NULL,
idLocales INT NOT NULL,
tipoPromocion VARCHAR(30) NOT NULL,
estadoPromocion VARCHAR(10) NOT NULL,
CONSTRAINT PK_PROMOCION_idPromocion PRIMARY KEY (idPromocion),
CONSTRAINT FK_PROMOCION_idLocales FOREIGN KEY (idLocales)  REFERENCES LOCALES(idLocales)
);


CREATE TABLE PRODUCTO (
idProducto INT NOT NULL,
idLocales INT NOT NULL,
detalle VARCHAR (20) NOT NULL,
precioPromocion NUMBER,
precioUnitario NUMBER,
CONSTRAINT PK_PRODUCTO_idProducto PRIMARY KEY (idProducto),
CONSTRAINT FK_PRODUCTO_idLocales FOREIGN KEY (idLocales) REFERENCES LOCALES (idLocales)
);

CREATE TABLE RUTAS (
idRuta INT NOT NULL,
idRepar INT NOT NULL,
recorrido VARCHAR (60) NOT NULL,
CONSTRAINT PK_RUTAS_idRuta PRIMARY KEY (idRuta),
CONSTRAINT FK_RUTAS_idRepar FOREIGN KEY (idRepar) REFERENCES REPARTIDOR (idRepar)
);

CREATE TABLE PEDIDO (
idPedido INTEGER NOT NULL,
idProducto INT NOT NULL,
nickName VARCHAR (30),
idRuta INTEGER NOT NULL,
detallePe VARCHAR (80) NOT NULL,
prioridad VARCHAR (10) NOT NULL,
CONSTRAINT PK_PEDIDO_idPedido PRIMARY KEY (idPedido),
CONSTRAINT FK_PEDIDO_idProducto FOREIGN KEY (idProducto) REFERENCES PRODUCTO(idProducto),
CONSTRAINT FK_PEDIDO_nickName FOREIGN KEY (nickName) REFERENCES USUARIO (nickName),
CONSTRAINT FK_PEDIDO_idRuta FOREIGN KEY (idRuta) REFERENCES RUTAS (idRuta)
);

CREATE TABLE DIRECCION (
direccionNombre VARCHAR (50) NOT NULL,
idLocales INT NOT NULL,
barrio VARCHAR (30) NOT NULL,
nroEdificio CHARACTER(6) NOT NULL,
CONSTRAINT PK_DIRECCION_direccionNombre PRIMARY KEY (direccionNombre),
CONSTRAINT FK_DIRECCION_idLocales FOREIGN KEY (idLocales) REFERENCES LOCALES (idLocales)
);

DROP TABLE DIRECCION;
DROP TABLE PROMOCION;
DROP TABLE PEDIDO;
DROP TABLE USUARIO;
DROP TABLE RUTAS;
DROP TABLE REPARTIDOR;
DROP TABLE PRODUCTO;
DROP TABLE LOCALES;